version: 2
jobs:
 build:
   environment:
     IMAGE_NAME: jordandelplanque/webserve
   docker:
     - image: jordandelplanque/webserve:firsttry
   steps:
     - checkout
     - run: docker build -t $IMAGE_NAME:firsttry .
     # deploy the image
     # - run: docker push pagepersos