version: 2
jobs:
 build:
  machine: true
  steps:
    - checkout
    - run: |
        ls 
        pwd
        docker login -u jordandelplanque -p ascasc0123
        docker pull jordandelplanque/webserve:firsttry
        docker build -t jordandelplanque/webserve:firsttry .
        docker push jordandelplanque/webserve:latest
    # deploy the image
    # - run: docker push pagepersos