version: 2
executors:
  my-executor:
    docker:
      - dockerfile: ./.circleci/Dockerfile
jobs:
 build:
   steps:
     - checkout
     - run: docker build -t pagepersos .
     # deploy the image
     # - run: docker push pagepersos