version: 2
jobs:
 build:
   docker:
     - dockerfile: ./.circleci/Dockerfile
   steps:
     - checkout
     - run: docker build -t pagepersos .
     # deploy the image
     # - run: docker push pagepersos