version: 2
jobs:
 build:
  machine: true
  steps:
    - checkout
    - run: |
        ls 
        pwd
        docker login -u jordandelplanque -p ascasc0123
        docker build -t jordandelplanque/webserve:latest -t  jordandelplanque/webserve:v0.2 .
        docker push jordandelplanque/webserve:latest
        docker push jordandelplanque/webserve:v0.2
    # deploy the image
    # - run: docker push pagepersos