version: 2
jobs:
 build:
  environment:
    IMAGE_NAME: jordandelplanque/webserve
  docker:
    - image: jordandelplanque/webserve:firsttry
      auth:
        username: jordandelplanque
        password: ascasc0123
  steps:
    - checkout
    - run: docker build -t jordandelplanque/webserve:firsttry .
    # deploy the image
    # - run: docker push pagepersos