version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker pull jordandelplanque/webserve:firsttry
     - run: docker build -t docker.io/jordandelplanque/webserve:firsttry .
     # deploy the image
     # - run: docker push pagepersos