version: 2
jobs:
 build:
  machine: true
  steps:
    - checkout
    - run: |
        docker login -u jordandelplanque -p ascasc0123
        docker pull jordandelplanque/webserve:firsttry
        docker run -d --name img jordandelplanque/webserve:firsttry .
    # deploy the image
    # - run: docker push pagepersos