version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout

     # build the application image
     - run: docker build -t pagepersos .

     # deploy the image
     # - run: docker push pagepersos